In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import requests

In [23]:
url = "https://financialmodelingprep.com/api/v3/income-statement/META?period=annual&apikey=08c0a5f0eb34249fcb61106ef358773b"

response = requests.get(url)
print(response)

income = response.json()

<Response [200]>

In [24]:
url = "https://financialmodelingprep.com/api/v3/balance-sheet-statement/META?period=annual&apikey=08c0a5f0eb34249fcb61106ef358773b"

response = requests.get(url)
print(response)

balance = response.json()

<Response [200]>

In [25]:
url = "https://financialmodelingprep.com/api/v3/cash-flow-statement/META?period=annual&apikey=08c0a5f0eb34249fcb61106ef358773b"

response = requests.get(url)
print(response)

cashflow = response.json()

<Response [200]>

In [ ]:
for date in range(0, len(date_list)):
    day = list(date_list[date])
    if not day[-1] == "0":
        day[-1] = str(int(day[-1]) - 1)
    else:
        day[-2:] = list(str(int("".join(day[-2:])) - 1))
    date_list[date] = "".join(day)

marketCap = []

for date in date_list:
    url = "https://financialmodelingprep.com/api/v3/historical-market-capitalization/" + ticker + "?from=" + date + "&to=" + date + "&apikey=08c0a5f0eb34249fcb61106ef358773b"
    response = requests.get(url)
    
    dailyCap = response.json()
    marketCap += dailyCap

print(f"Market cap processing response: {response}")

In [34]:
marketCap = []

for date in date_list:
    url = "https://financialmodelingprep.com/api/v3/historical-market-capitalization/META?from=" + date + "&to=" + date + "&apikey=08c0a5f0eb34249fcb61106ef358773b"
    response = requests.get(url)
    print(response)

    dailyCap = response.json()
    marketCap += dailyCap

<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>

In [35]:
marketCap

[{'symbol': 'META', 'date': '2022-12-30', 'marketCap': 317456920000},
 {'symbol': 'META', 'date': '2021-12-30', 'marketCap': 963201662308},
 {'symbol': 'META', 'date': '2020-12-30', 'marketCap': 785704300000},
 {'symbol': 'META', 'date': '2019-12-30', 'marketCap': 585472592116}]

In [30]:
reportsCount = len(cashflow)

for x in range(0, reportsCount):
    if x == 0:
        df = pd.DataFrame(income[x] | balance[x] | cashflow[x] | marketCap[x], index=[x])
    else:
        df = pd.concat([df, pd.DataFrame(income[x] | balance[x] | cashflow[x] | marketCap[x], index=[x])])

NameError: name 'marketCap' is not defined

In [21]:
def remove_statics(df, keys=["reportedCurrency", "cik", "fillingDate", "acceptedDate", "calendarYear", "period", "link", "finalLink"]):
    for key in keys:
        if key in df.columns:
            df.pop(key)
    return df

df = remove_statics(df)

In [24]:
for i, row in df.iterrows():
    ifor_val = 0
    if not i == 0:
        if df["marketCap"][i] < df["marketCap"][i-1]:
            ifor_val = 1
    df.at[i, "target"] = ifor_val

In [25]:
df

,date,symbol,revenue,costOfRevenue,grossProfit,grossProfitRatio,researchAndDevelopmentExpenses,generalAndAdministrativeExpenses,sellingAndMarketingExpenses,sellingGeneralAndAdministrativeExpenses,...,totalStockholdersEquity,totalEquity,totalLiabilitiesAndStockholdersEquity,minorityInterest,totalLiabilitiesAndTotalEquity,totalInvestments,totalDebt,netDebt,marketCap,target
0,2024-09-27,AAPL,391035000000,210352000000,180683000000,0.462063,31370000000,0,0,26097000000,...,56950000000,56950000000,364980000000,0,364980000000,126707000000,106629000000,76686000000,3456027602100,0.0
1,2023-09-29,AAPL,383285000000,214137000000,169148000000,0.441311,29915000000,0,0,24932000000,...,62146000000,62146000000,352583000000,0,352583000000,132134000000,111088000000,81123000000,2670779095140,1.0
2,2022-09-23,AAPL,394328000000,223546000000,170782000000,0.433096,26251000000,0,0,25094000000,...,50672000000,50672000000,352755000000,0,352755000000,145463000000,132480000000,108834000000,2411450364260,1.0
3,2021-09-24,AAPL,365817000000,212981000000,152836000000,0.417794,21914000000,0,0,21973000000,...,63090000000,63090000000,351002000000,0,351002000000,155576000000,136522000000,101582000000,2422287817320,0.0
4,2020-09-25,AAPL,274515000000,169559000000,104956000000,0.382332,18752000000,0,0,19916000000,...,65339000000,65339000000,323888000000,0,323888000000,153814000000,122278000000,84262000000,1915229798160,1.0

In [31]:
for i in df.index:
    ifor_val = 0
    if not i == 0:
        if df["marketCap"][i-1] > df["marketCap"][i]:
            ifor_val = 1
    df.at[i, "target"] = ifor_val

4
3
2
1
0

In [32]:
df

,date,symbol,revenue,costOfRevenue,grossProfit,grossProfitRatio,researchAndDevelopmentExpenses,generalAndAdministrativeExpenses,sellingAndMarketingExpenses,sellingGeneralAndAdministrativeExpenses,...,totalStockholdersEquity,totalEquity,totalLiabilitiesAndStockholdersEquity,minorityInterest,totalLiabilitiesAndTotalEquity,totalInvestments,totalDebt,netDebt,marketCap,target
0,2024-09-27,AAPL,391035000000,210352000000,180683000000,0.462063,31370000000,0,0,26097000000,...,56950000000,56950000000,364980000000,0,364980000000,126707000000,106629000000,76686000000,3456027602100,1.0
1,2023-09-29,AAPL,383285000000,214137000000,169148000000,0.441311,29915000000,0,0,24932000000,...,62146000000,62146000000,352583000000,0,352583000000,132134000000,111088000000,81123000000,2670779095140,1.0
2,2022-09-23,AAPL,394328000000,223546000000,170782000000,0.433096,26251000000,0,0,25094000000,...,50672000000,50672000000,352755000000,0,352755000000,145463000000,132480000000,108834000000,2411450364260,0.0
3,2021-09-24,AAPL,365817000000,212981000000,152836000000,0.417794,21914000000,0,0,21973000000,...,63090000000,63090000000,351002000000,0,351002000000,155576000000,136522000000,101582000000,2422287817320,1.0
4,2020-09-25,AAPL,274515000000,169559000000,104956000000,0.382332,18752000000,0,0,19916000000,...,65339000000,65339000000,323888000000,0,323888000000,153814000000,122278000000,84262000000,1915229798160,0.0

In [39]:
df.drop(df.tail(1).index, inplace=True)

In [41]:
df_for_ml = pd.DataFrame()
df_for_ml = pd.concat([df_for_ml, df])
df_for_ml

,date,symbol,revenue,costOfRevenue,grossProfit,grossProfitRatio,researchAndDevelopmentExpenses,generalAndAdministrativeExpenses,sellingAndMarketingExpenses,sellingGeneralAndAdministrativeExpenses,...,totalStockholdersEquity,totalEquity,totalLiabilitiesAndStockholdersEquity,minorityInterest,totalLiabilitiesAndTotalEquity,totalInvestments,totalDebt,netDebt,marketCap,target
0,2024-09-27,AAPL,391035000000,210352000000,180683000000,0.462063,31370000000,0,0,26097000000,...,56950000000,56950000000,364980000000,0,364980000000,126707000000,106629000000,76686000000,3456027602100,1.0
1,2023-09-29,AAPL,383285000000,214137000000,169148000000,0.441311,29915000000,0,0,24932000000,...,62146000000,62146000000,352583000000,0,352583000000,132134000000,111088000000,81123000000,2670779095140,1.0
2,2022-09-23,AAPL,394328000000,223546000000,170782000000,0.433096,26251000000,0,0,25094000000,...,50672000000,50672000000,352755000000,0,352755000000,145463000000,132480000000,108834000000,2411450364260,0.0
3,2021-09-24,AAPL,365817000000,212981000000,152836000000,0.417794,21914000000,0,0,21973000000,...,63090000000,63090000000,351002000000,0,351002000000,155576000000,136522000000,101582000000,2422287817320,1.0